#!/usr/bin/env zsh

if [ ! -f /etc/keys/validator.priv ]; then
    sawadm keygen &&
        sawset genesis \
               -k /etc/sawtooth/keys/validator.priv \
               -o config-genesis.batch &&
        sawset proposal create \
               -k /etc/sawtooth/keys/validator.priv \
               sawtooth.consensus.algorithm.name=Devmode \
               sawtooth.consensus.algorithm.version=0.1 \
               sawtooth.validator.batch_injectors=block_info \
               -o config.batch &&
        sawadm genesis config-genesis.batch config.batch
fi;
sawtooth-validator -vv \
                   --endpoint       tcp://127.0.0.1:8800 \
                   --bind component:tcp://127.0.0.1:4004 \
                   --bind   network:tcp://127.0.0.1:8800 \
                   --bind consensus:tcp://127.0.0.1:5050
