#!/usr/bin/env zsh

if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
    sawadm keygen
fi;

# # peers=`print "keys *" | redis-cli`
# for i in ${(f)"${peers}"}; do # print ${peers}
# 		 print " $i"
# done
torsocks sawtooth-validator -vv \
                   --scheduler serial \
				   --peering static \
                   --network-auth challenge \
\
                   --endpoint       tcp://127.0.0.1:8800 \
                   --bind component:tcp://127.0.0.1:4004 \
                   --bind   network:tcp://127.0.0.1:8800 \
                   --bind consensus:tcp://127.0.0.1:5050

# sawset genesis \
#            -k /etc/sawtooth/keys/validator.priv \
#            -o config-genesis.batch &&
# sawset proposal create \
#            -k /etc/sawtooth/keys/validator.priv \
#            sawtooth.consensus.algorithm.name=pbft \
#            sawtooth.consensus.algorithm.version=1.0 \
#            sawtooth.validator.batch_injectors=block_info \
#            -o config.batch &&
# sawadm genesis config-genesis.batch config.batch

